apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: finalcapstone
  labels: 
    name: myapp
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 8092
    targetPort: 8092
    nodePort: 32400
